version: "3"
services:
  samba:
    image: "dperson/samba"
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - "nas:/samba/nas"
    environment:
      - USERID=1000
      - GROUPID=1000
    command: ["-s", "Nas;/samba/nas;no;no;yes;", "-u", "majik;majik"]
    restart: "always"

  aria2:
    image: "vimagick/aria2"
    ports:
      - "6800:6800"
    volumes:
      - "./aria2/aria2.conf:/etc/aria2/aria2.conf"
      - "nas:/home/aria2"
    restart: "always"

volumes:
  - nas
